language: ruby
rvm:
- 2.4.0
before_script:
- bundle install --deployment --path vendor/bundle
- bundle exec rake db:setup
- bundle exec rake db:test:prepare
script:
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: sHPsKsFsuPsUWz/M1rWhSoMRzP/PCUFL5dX7vBzDjujM7ULauJe1uPGR1k3JW+XOb8M5sfDHUuvdXYy6iB8jQY3pS40k6vxuDAADaQdnu1C+DfFJS3IVZJ3JV70//UJ0ypo9FfatfZ506KU2eDGEC1i7QqW0feT0Uc2hP6DdaxtKQyVfKDcDhXKaxw+0cYKR4btEd/VTxtG9ikRBmx33GSoKzIZ74cecKzAFL1slk++X1z4zSAaflkRJT1JC6m17Zv9njr+YEB+oj7a/DjgCkZFH37Ld0X9cYdIv2xPGoA5Mh98QNurdLRTMciBtvPbY4QKBvzWjRZwgNHwDYTmCgE5QXb0WhnfQ8Q8KptiPjjN9nO4+7aMfrB/rGfGyVcnavu6CSN03cJmNT4ImTMX6vwYrmD/vpeluHuKR0grWU9OMaUW70sKsDhv4yGyMP/xb0FlcQcCozE5h2nlpLRD7Ek5JUyHH2H96R5P3OVmhzUGpqRNURBrC9f+2bilD04phvv3Bh6ePW5TOGgElKTz8vKYdeMBKSBTNlP08tKMOqyhwM69MYGqQELphg1ZONr89wXwlLr7glJqZzPIw/qyrlJeEvMyyAL412RH3s1Kw9kQ5i1MDkKn7dJ/O7Cg8g0HLsckQycJ/iuPD2UXaain0k1/2ctFl8J4waFEbozsOYZM=
