language: ruby
rvm:
- 2.4.0
before_script:
- bundle install --deployment --path vendor/bundle
- bundle exec rake db:setup
- bundle exec rake db:test:prepare
script:
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false
deploy:
  api_key:
    secure: tI72G+YcOQuXXeAUQMtJhiXUU87iowH7UvyjW4gtODuK/oCcwy6WnY0I3iFgWDaw6ulxxgASqGXMuNWPIe6uSKbZKnrnoXpa6NFv1/E+4wh1P0MO2gWO6D5zJJFCgBbTMPjC9SJcFDSzhmz05v6bsGnHTGetan44Ykj+eaAccx6Ff9gPPtpjQR4XkUiwsP1NvGIJxfDBchG1adGx54culDPBIH5fGkkDh2Jfkki7rXd2fetxWPqkc77Lv7roe8b+fmwPnhuIFX5HyMUad1jEiFIN8GNhCTE4cDkzNFjDcIrrO0pBdnGApEChcuZEFGKjYC2QdglZG4IerV5B+8PZSeF0IgrLhnVFhmAUxTW3R3reAM8Yo7EqOPK+qSOt/pb8O4mXYSP0DI1Djj01QXDJaP+x+tOG2AFw8wQkTCrv/SxFWIpUmGgSYHKds30KA5941l7mNKua7/GX/rf8v38EqrKgT5DWbvtDhZEmRQDnDASXcjrveSIr0qi2ChjUuuDog18RYCbY+gBsu8Y0M+XrT7PayBnHCjCeVRRJwgln7QIuNoKXtABfKTtXGuo341FeHkHonreiqEo61GxQBsHF0cnDhyDfaU1tV3MspNVj+Hyxiue0PEpGCPxWXWdYINgWWDR6/DESdmzo1HCVroKnTtAUmnlgIKupxGMlMIKs9zU=
